name: (M) Deploy to Prod
on:
  workflow_dispatch:
permissions:
  contents: write
jobs:
  release:
    name: Tag code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7.0.1
        with:
          fetch-depth: 0

      - name: Determine expected commit SHA
        run: |
          expected_sha=$(git rev-list -n1 "$(git describe --tags --abbrev=0)")
          echo "$expected_sha"
          echo "expected_sha=$expected_sha" >> "$GITHUB_ENV"

      - uses: ./.github/actions/dingorunner
        env:
          runner: deploy
          terminus_api: ${{ secrets.TERMINUS_API }}
          SSH_PRIVATE_KEY: ${{ secrets.PANTHEON_DEPLOY_KEY}}
          site_name: ${{ secrets.TERMINUS_SITE_NAME }}
          env: live
          flags:
          expected_sha: ${{ env.expected_sha }}
